### ISSUE TITLE
Creating NS record fails

### ISSUE THREAD

**Issue by dekimsey** [akamai/cli-dns#2]
akamai version 1.1.3

```
akamai dns add-record NS example.com --name=foo --target=ns-1337.awsdns-53.org --ttl=600
Adding new NS record..... panic: interface conversion: dns.DNSRecord is *dns.NsRecord, not *dns.CnameRecord

goroutine 1 [running]:
main.cmdCreateRecord(0xc000178160, 0x10100, 0xc000178160)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/command_add_record.go:152 +0x4219
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.HandleAction(0x13afb40, 0x1443608, 0xc000178160, 0xc0000ba600, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x142a3b3, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc0000aad00, 0xc0000c1e40, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:379 +0x7ef
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.startApp(0x142c550, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:298 +0x808
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.Command.Run(0x142c550, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/command.go:98 +0x1237
github.com/akamai/cli-dns/vendor/github.com/urfave/cli.(*App).Run(0xc0000aab60, 0xc0000bc000, 0x7, 0x7, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/Users/dshafik/src/go/src/github.com/akamai/cli-dns/akamai-dns.go:37 +0xcf
```

Appears to be an issue with the CNAME type conversion on command_add_record.go#L152

Adding a `.` to the NS target bypasses this bug.

**Comment by akamaimike** [comment]
Thanks for reporting this issue. We will be closing this issue due to inactivity. Please feel free to open a new issue if needed. Kind regards, Mike
